name: GitHub Actions Demo
on:
  push:
    tags:
      - "v*"
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create ticket
        run: sh ./.github/scripts/createTicket.sh
        env:
          TRACKER_OAUTH: ${{ secrets.TRACKER_OAUTH }}
          TRACKER_ORGID: ${{ secrets.TRACKER_ORGID }}
          REPO_NAME: ${{ secrets.REPO_NAME }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci
      - name: Run autotests
        run: sh ./.github/scripts/test.sh
        env:
          TRACKER_OAUTH: ${{ secrets.TRACKER_OAUTH }}
          TRACKER_ORGID: ${{ secrets.TRACKER_ORGID }}
          REPO_NAME: ${{ secrets.REPO_NAME }}

      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version

      - name: Docker build
        run: sh ./.github/scripts/createTicket.sh
        env:
          TRACKER_OAUTH: ${{ secrets.TRACKER_OAUTH }}
          TRACKER_ORGID: ${{ secrets.TRACKER_ORGID }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
